services:
  - type: static
    name: Kingdom Game Client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZGFxdGxremlvZ2JqZnhhbHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0ODQxNzIsImV4cCI6MjA4MTA2MDE3Mn0.Lobw8h8oE8A5RSgvOa9OHhFf6UetheGycH3vEGRtVa0
      - key: VITE_SUPABASE_URL
        value: https://qidaqtlkziogbjfxalvm.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        value: sb_publishable_s4azmiksBZTAXEJsNeWB6w_Zpgtt8QF
